language: php

php:
  - 7.4
  - 8.0
  - hhvm

matrix:
  fast_finish: true
  allow_failures:
    - php: hhvm

before_script:
  - travis_retry composer self-update
  - travis_retry composer update --no-interaction --prefer-source

script:
  - mkdir -p build/logs
  - vendor/bin/phpspec run -v
  - vendor/bin/phpunit --coverage-text
